WebUI/Controllers/ClientsController.cs
using Core.Domain.Entities;
using Microsoft.AspNetCore.Mvc;
using System.Text;
using System.Text.Json;

namespace WebUI.Controllers
{
    public class ClientsController : Controller
    {

        private readonly ILogger<ClientsController> _logger;
        private readonly HttpClient _httpClient;
        private const string _APIURL = " https://localhost:44375";


        public ClientsController(ILogger<ClientsController> logger)
        {
            _logger = logger;
            _httpClient = new HttpClient();
            _httpClient.BaseAddress = new Uri(_APIURL);
        }
        // GET: Clients
        public async Task<IActionResult> Index()
        {
            HttpResponseMessage response = await _httpClient.GetAsync("/api/Client");
            if (response.IsSuccessStatusCode)
            {
                var data = await response.Content.ReadAsStringAsync();
                var options = new JsonSerializerOptions
                {
                    PropertyNameCaseInsensitive = true
                };
                var clients = JsonSerializer.Deserialize<List<Client>>(data, options);
                return View(clients);
            }
            return View("");
        }


        // GET: Clients/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            HttpResponseMessage response = await _httpClient.GetAsync($"/api/Client/{id}");
            if (response.IsSuccessStatusCode)
            {
                var options = new JsonSerializerOptions
                {
                    PropertyNameCaseInsensitive = true
                };
                var data = await response.Content.ReadAsStringAsync();
                var client = JsonSerializer.Deserialize<Client>(data, options);
                return View(client);
            }
            return NotFound();
        }

        // GET: Clients/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Clients/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FirstName,LastName,Email,PhoneNumber,Second_PhoneNumber,Third_PhoneNumber," +
            "Job,IdCard_Number,IdCard_ImgUrl,Passport_Number,Passport_ImgUrl,Id,IsActive,CreationDate,DeleteDate")] Client client)
        {
            if (ModelState.IsValid)
            {
                HttpContent content = new StringContent(JsonSerializer.Serialize(client), Encoding.UTF8, "application/json");
                HttpResponseMessage response = await _httpClient.PostAsync("/api/Client/Add-Client", content);
                if (response.IsSuccessStatusCode)
                {
                    //go back to main page Index
                    return RedirectToAction(nameof(Index));
                }

            }
            return BadRequest("Couldn't create a client ");
        }

        // GET: Clients/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            HttpResponseMessage response = await _httpClient.GetAsync($"/api/Client/{id}");
            if (response.IsSuccessStatusCode)
            {
                var options = new JsonSerializerOptions
                {
                    PropertyNameCaseInsensitive = true
                };
                var data = await response.Content.ReadAsStringAsync();
                var client = JsonSerializer.Deserialize<Client>(data, options);

                if (client == null)
                {
                    return NotFound();
                }
                return View(client);
            }
            return NotFound();



        }

        // POST: Clients/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("FirstName,LastName,Email,PhoneNumber,Second_PhoneNumber,Third_PhoneNumber,Job,IdCard_Number,IdCard_ImgUrl,Passport_Number,Passport_ImgUrl,Id,IsActive,CreationDate,DeleteDate")] Client client)
        {
            if (id != client.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                HttpContent content = new StringContent(JsonSerializer.Serialize(client), Encoding.UTF8, "application/json");
                try
                {

                    HttpResponseMessage response = await _httpClient.PutAsync($"/api/Client/{client.Id}", content);
                    if (response.IsSuccessStatusCode)
                    {
                        var options = new JsonSerializerOptions
                        {
                            PropertyNameCaseInsensitive = true
                        };
                        var data = await response.Content.ReadAsStringAsync();
                        var res = JsonSerializer.Deserialize<Client>(data, options);
                        return View(client);
                    }

                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
                }
                return NotFound("Client is not Found in DB");
            }
            return NotFound();
        }

        // GET: Clients/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            HttpResponseMessage response = await _httpClient.GetAsync($"/api/Client/{id}");
            if (response.IsSuccessStatusCode)
            {
                var options = new JsonSerializerOptions
                {
                    PropertyNameCaseInsensitive = true
                };
                var data = await response.Content.ReadAsStringAsync();
                var client = JsonSerializer.Deserialize<Client>(data, options);

                if (client == null)
                {
                    return NotFound();
                }
                return View(client);
            }
            return NotFound();
        }

        // POST: Clients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            HttpResponseMessage response = await _httpClient.DeleteAsync($"/api/Client/{id}");
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction(nameof(Index));
            }
            return BadRequest("error occured while working with db");
        }


    }
}

WebUI/Controllers/OrdersController.cs
using Core.Domain.Entities;
using Microsoft.AspNetCore.Mvc;
using System.Text;
using System.Text.Json;

namespace WebUI.Controllers
{
    public class OrdersController : Controller
    {
        private readonly ILogger<OrdersController> _logger;
        private readonly HttpClient _httpClient;
        private const string _APIURL = " https://localhost:44375";

        public OrdersController(ILogger<OrdersController> logger)
        {
            _logger = logger;
            _httpClient = new HttpClient();
            _httpClient.BaseAddress = new Uri(_APIURL);
        }

        public async Task<IActionResult> Index()
        {
            HttpResponseMessage response = await _httpClient.GetAsync("/api/Order");
            if (response.IsSuccessStatusCode)
            {
                var data = await response.Content.ReadAsStringAsync();
                var options = new JsonSerializerOptions { PropertyNameCaseInsensitive = true };
                var orders = JsonSerializer.Deserialize<List<Order>>(data, options);
                return View(orders);
            }
            return View(new List<Order>());
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null) return NotFound();
            var response = await _httpClient.GetAsync($"/api/Order/{id}");
            if (response.IsSuccessStatusCode)
            {
                var data = await response.Content.ReadAsStringAsync();
                var options = new JsonSerializerOptions { PropertyNameCaseInsensitive = true };
                var order = JsonSerializer.Deserialize<Order>(data, options);
                return View(order);
            }
            return NotFound();
        }

        public IActionResult Create() => View();

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("OrderDate,TotalAmount,Status,Status_Reason,TravelPlan_Id,ClientId,Id,IsActive,CreationDate,DeleteDate")] Order order)
        {
            if (!ModelState.IsValid) return View(order);
            var content = new StringContent(JsonSerializer.Serialize(order), Encoding.UTF8, "application/json");
            var response = await _httpClient.PostAsync("/api/Order", content);
            if (response.IsSuccessStatusCode) return RedirectToAction(nameof(Index));
            return BadRequest("Couldn't create order");
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null) return NotFound();
            var response = await _httpClient.GetAsync($"/api/Order/{id}");
            if (response.IsSuccessStatusCode)
            {
                var data = await response.Content.ReadAsStringAsync();
                var options = new JsonSerializerOptions { PropertyNameCaseInsensitive = true };
                var order = JsonSerializer.Deserialize<Order>(data, options);
                if (order == null) return NotFound();
                return View(order);
            }
            return NotFound();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("OrderDate,TotalAmount,Status,Status_Reason,TravelPlan_Id,ClientId,Id,IsActive,CreationDate,DeleteDate")] Order order)
        {
            if (id != order.Id) return NotFound();
            if (!ModelState.IsValid) return View(order);
            var content = new StringContent(JsonSerializer.Serialize(order), Encoding.UTF8, "application/json");
            var response = await _httpClient.PutAsync($"/api/Order/{order.Id}", content);
            if (response.IsSuccessStatusCode) return RedirectToAction(nameof(Index));
            return NotFound();
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return NotFound();
            var response = await _httpClient.GetAsync($"/api/Order/{id}");
            if (response.IsSuccessStatusCode)
            {
                var data = await response.Content.ReadAsStringAsync();
                var options = new JsonSerializerOptions { PropertyNameCaseInsensitive = true };
                var order = JsonSerializer.Deserialize<Order>(data, options);
                if (order == null) return NotFound();
                return View(order);
            }
            return NotFound();
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var response = await _httpClient.DeleteAsync($"/api/Order/{id}");
            if (response.IsSuccessStatusCode) return RedirectToAction(nameof(Index));
            return BadRequest("error occured while working with db");
        }
    }
}

WebUI/Controllers/UsersController.cs
using Core.Domain.Entities;
using Microsoft.AspNetCore.Mvc;
using System.Text;
using System.Text.Json;

namespace WebUI.Controllers
{
    public class UsersController : Controller
    {
        private readonly ILogger<UsersController> _logger;
        private readonly HttpClient _httpClient;
        private const string _APIURL = " https://localhost:44375";

        public UsersController(ILogger<UsersController> logger)
        {
            _logger = logger;
            _httpClient = new HttpClient();
            _httpClient.BaseAddress = new Uri(_APIURL);
        }

        public async Task<IActionResult> Index()
        {
            HttpResponseMessage response = await _httpClient.GetAsync("/api/User");
            if (response.IsSuccessStatusCode)
            {
                var data = await response.Content.ReadAsStringAsync();
                var options = new JsonSerializerOptions { PropertyNameCaseInsensitive = true };
                var users = JsonSerializer.Deserialize<List<User>>(data, options);
                return View(users);
            }
            return View(new List<User>());
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null) return NotFound();
            HttpResponseMessage response = await _httpClient.GetAsync($"/api/User/{id}");
            if (response.IsSuccessStatusCode)
            {
                var data = await response.Content.ReadAsStringAsync();
                var options = new JsonSerializerOptions { PropertyNameCaseInsensitive = true };
                var user = JsonSerializer.Deserialize<User>(data, options);
                return View(user);
            }
            return NotFound();
        }

        public IActionResult Create() => View();

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FirstName,LastName,Email,Password,PhoneNumber,Second_PhoneNumber,Third_PhoneNumber,IdCard_Number,Passport_Number,Id,IsActive,CreationDate,DeleteDate")] User user)
        {
            if (!ModelState.IsValid) return View(user);
            var content = new StringContent(JsonSerializer.Serialize(user), Encoding.UTF8, "application/json");
            var response = await _httpClient.PostAsync("/api/User", content);
            if (response.IsSuccessStatusCode) return RedirectToAction(nameof(Index));
            return BadRequest("Couldn't create user");
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null) return NotFound();
            var response = await _httpClient.GetAsync($"/api/User/{id}");
            if (response.IsSuccessStatusCode)
            {
                var data = await response.Content.ReadAsStringAsync();
                var options = new JsonSerializerOptions { PropertyNameCaseInsensitive = true };
                var user = JsonSerializer.Deserialize<User>(data, options);
                if (user == null) return NotFound();
                return View(user);
            }
            return NotFound();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("FirstName,LastName,Email,Password,PhoneNumber,Second_PhoneNumber,Third_PhoneNumber,IdCard_Number,Passport_Number,Id,IsActive,CreationDate,DeleteDate")] User user)
        {
            if (id != user.Id) return NotFound();
            if (!ModelState.IsValid) return View(user);
            var content = new StringContent(JsonSerializer.Serialize(user), Encoding.UTF8, "application/json");
            var response = await _httpClient.PutAsync($"/api/User/{user.Id}", content);
            if (response.IsSuccessStatusCode) return RedirectToAction(nameof(Index));
            return NotFound();
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return NotFound();
            var response = await _httpClient.GetAsync($"/api/User/{id}");
            if (response.IsSuccessStatusCode)
            {
                var data = await response.Content.ReadAsStringAsync();
                var options = new JsonSerializerOptions { PropertyNameCaseInsensitive = true };
                var user = JsonSerializer.Deserialize<User>(data, options);
                if (user == null) return NotFound();
                return View(user);
            }
            return NotFound();
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var response = await _httpClient.DeleteAsync($"/api/User/{id}");
            if (response.IsSuccessStatusCode) return RedirectToAction(nameof(Index));
            return BadRequest("error occured while working with db");
        }
    }
}

WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebUI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap-icons/font/bootstrap-icons.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebUI.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/ClientGlobalStyle.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/custom-actions.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand d-flex align-items-center" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/logo.png" alt="logo" style="height:30px;" class="me-2" />
                    <span>WebUI</span>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                       <!-- Espace Client-->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarClient" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Clients
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarClient">
                                <li><a class="dropdown-item" asp-controller="Clients" asp-action="Index">List Clients</a></li>
                                <li><a class="dropdown-item" asp-controller="Clients" asp-action="Create">New Client</a></li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarUser" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Users
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarUser">
                                <li><a class="dropdown-item" asp-controller="Users" asp-action="Index">List Users</a></li>
                                <li><a class="dropdown-item" asp-controller="Users" asp-action="Create">New User</a></li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarOrder" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Orders
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarOrder">
                                <li><a class="dropdown-item" asp-controller="Orders" asp-action="Index">List Orders</a></li>
                                <li><a class="dropdown-item" asp-controller="Orders" asp-action="Create">New Order</a></li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarTravelPlan" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Travel Plans
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarTravelPlan">
                                <li><a class="dropdown-item" asp-controller="TravelPlans" asp-action="Index">List Travel Plans</a></li>
                                <li><a class="dropdown-item" asp-controller="TravelPlans" asp-action="Create">New Travel Plan</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid m-0 p-5">
        <main role="main" class="m-0 p-0 pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - WebUI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>